const typesMapping = {
    0: "Gaming",
    1: "Technology",
    2: "Science",
    3: "Art",
    4: "Music",
    5: "Literature",
    6: "History",
    7: "Health & Fitness",
    8: "Travel",
    9: "Food & Cooking",
    10: "Fashion",
    11: "Business",
    12: "Finance",
    13: "Education",
    14: "Sports",
    15: "Entertainment",
    16: "Photography",
    17: "Film & TV",
    18: "Politics",
    19: "Psychology",
    20: "Self-Improvement",
    21: "Philosophy",
    22: "Environment",
    23: "Parenting",
    24: "Pets & Animals",
    25: "Home & Garden",
    26: "Relationships",
    27: "Real Estate",
    28: "Social Media",
    29: "Books",
    30: "Other",
};

module.exports = typesMapping;